### ISSUE TITLE
Switch to Tapestry 5.3.8 for Java 8 Support

### ISSUE THREAD

**Issue by derkoe** [porscheinformatik/tapestry-csrf-protection#15]

**Comment by naboujina** [comment]
Hello,
Thanks for this module. It's the first time I used it. I have some problems with it. The version of my app is 5.3.8 and I added the dependency in the pom (1.2.0.BUILD-SNAPSHOT version). The fact is it seems like nothing happens. I don't see the hidden field added, the csrf token, nothing.....
Do you have any documentation or tuto to follow to know if I have missed something or not please ?
Please. Thanks.
