### ISSUE TITLE
CSRF protection module is not compatible with the latest version of Tapestry (ver. 5.7.+)

### ISSUE THREAD

**Issue by alexis-pasialis** [porscheinformatik/tapestry-csrf-protection#21]
The migration tool (found at https://tapestry.apache.org/release-notes-570.html) needs to run.

**Comment by derkoe** [comment]
Closed via #22

**Comment by derkoe** [comment]
@alexis-pasialis could you try the `3.0.0.BUILD-SNAPSHOT` in  https://oss.sonatype.org/content/repositories/snapshots?

**Comment by alexis-pasialis** [comment]
@derkoe I've tested the above snapshop and it works perfectly. Thanks!

**Comment by derkoe** [comment]
Released in [3.0.0.RELEASE](https://github.com/porscheinformatik/tapestry-csrf-protection/releases/tag/v3.0.0.RELEASE)
